name: CI - Gestion de Citas Inteligente App

on:
  push:
    branches:
      - develop
      - qa
      - main
  pull_request:
    branches:
      - develop
      - qa
      - main

jobs:
  validate-docker-compose:
    name: Validate Docker Compose files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Validate docker-compose.develop.yml
        run: docker compose -f docker-compose.develop.yml config

      - name: Validate docker-compose.qa.yml
        run: docker compose -f docker-compose.qa.yml config

      - name: Validate docker-compose.main.yml
        run: docker compose -f docker-compose.main.yml config